import { Inter } from 'next/font/google'
import './globals.css'
import {getServerSession} from "next-auth";
import SessionProvider from "@/contexts/SessionProvider";
import { authOptions } from "@/app/api/auth/[...nextauth]";
import '../prism/prism.css'
import Script from "next/script";

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'AlgoExpert | Ace the Coding Interview',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }) {

  const session = await getServerSession(authOptions);


  return (
    <html lang="en">
    <Script src={'/public/prism.js'} strategy={'lazyOnload'}/>
      <body className={inter.className}>
        <SessionProvider session={session}>
          {children}
        </SessionProvider>
      </body>
    </html>
  )
}
